import { ArrowRight, CheckCircle2, MessageCircle, ShieldCheck, Truck, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { products } from '../data/products';
import ProductCard from '../components/ProductCard';

export default function Home(){return <>
<section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">Hakeem Syed Sharafat Ali Shah</span><h1>Traditional care, <em>modern shopping.</em></h1><p>Explore selected herbal and Unani products through a simple, trustworthy online store experience.</p><div className="hero-buttons"><Link className="btn btn-dark" to="/shop">Explore Shop <ArrowRight size={17}/></Link><a className="btn btn-outline" href="https://wa.me/923156928894" target="_blank" rel="noreferrer"><MessageCircle size={17}/> WhatsApp</a></div><div className="hero-trust"><span><CheckCircle2/> Easy ordering</span><span><ShieldCheck/> Secure checkout UI</span></div></div><div className="hero-visual"><img src="/images/natural-banner.png" alt="Traditional herbal products"/></div></div></section>
<section className="intro"><div className="container intro-grid"><div><span className="eyebrow">قدرتی علاج، مکمل اعتماد</span><h2>Traditional products with a professional storefront.</h2><p>Our portfolio-ready frontend brings together product discovery, cart management, customer details, payment selection, WhatsApp ordering and responsive design.</p><Link to="/about" className="text-link">Learn more <ArrowRight size={16}/></Link></div><img src="/images/natural-profile.png" alt="Hakeem Syed Sharafat Ali Shah"/></div></section>
<section className="features"><div className="container feature-grid"><div><Truck/><strong>Simple ordering</strong><span>Clear cart and checkout flow.</span></div><div><ShieldCheck/><strong>Customer friendly</strong><span>Clean forms and useful feedback.</span></div><div><Sparkles/><strong>Responsive UI</strong><span>Designed for mobile and desktop.</span></div></div></section>
<section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">Featured Collection</span><h2>Popular products</h2></div><Link to="/shop" className="text-link">View all <ArrowRight size={16}/></Link></div><div className="product-grid">{products.slice(0,4).map(p=><ProductCard key={p.id} product={p}/>)}</div></div></section>
<section className="gallery-strip"><div className="container"><div className="section-head"><div><span className="eyebrow">From the collection</span><h2>Herbal product gallery</h2></div></div><div className="gallery-grid">{['natural-product-1.png','natural-product-2.png','natural-product-3.png','natural-product-4.png'].map(x=><img key={x} src={`/images/${x}`} alt="Herbal product"/>)}</div></div></section>
</>}
